Traceback (most recent call last):
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/carlosdavid/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------


# Read as whitespace-delimited file
# stations = pd.read_csv(
#     station_list_path,
#     delim_whitespace=True,
#     header=None,
#     usecols=[0,1,2,3,4,5,6],
#     names=["id", "lat", "lon", "elev_m", "name1", "name2", "name3"],
#     engine="python"
# )

stations = pd.read_fwf(
    station_list_path,
    header=None,
    names=['id','lat','lon','elev_m','name','datei','datef','records'])

# The station name may be split across multiple columns, so join them
stations["name"] = stations[["name1","name2","name3"]].fillna("").agg(" ".join, axis=1).str.strip()

# Keep only relevant columns
stations = stations[["id","lat","lon","elev_m","name"]]

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[3], line 17[0m
[1;32m     11[0m stations [38;5;241m=[39m pd[38;5;241m.[39mread_fwf(
[1;32m     12[0m     station_list_path,
[1;32m     13[0m     header[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m     14[0m     names[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mid[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mlat[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mlon[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124melev_m[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mname[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mdatei[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mdatef[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mrecords[39m[38;5;124m'[39m])
[1;32m     16[0m [38;5;66;03m# The station name may be split across multiple columns, so join them[39;00m
[0;32m---> 17[0m stations[[38;5;124m"[39m[38;5;124mname[39m[38;5;124m"[39m] [38;5;241m=[39m stations[[[38;5;124m"[39m[38;5;124mname1[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mname2[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mname3[39m[38;5;124m"[39m]][38;5;241m.[39mfillna([38;5;124m"[39m[38;5;124m"[39m)[38;5;241m.[39magg([38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m[38;5;241m.[39mjoin, axis[38;5;241m=[39m[38;5;241m1[39m)[38;5;241m.[39mstr[38;5;241m.[39mstrip()
[1;32m     19[0m [38;5;66;03m# Keep only relevant columns[39;00m
[1;32m     20[0m stations [38;5;241m=[39m stations[[[38;5;124m"[39m[38;5;124mid[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mlat[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mlon[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124melev_m[39m[38;5;124m"[39m,[38;5;124m"[39m[38;5;124mname[39m[38;5;124m"[39m]]

File [0;32m~/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/pandas/core/frame.py:4108[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   4106[0m     [38;5;28;01mif[39;00m is_iterator(key):
[1;32m   4107[0m         key [38;5;241m=[39m [38;5;28mlist[39m(key)
[0;32m-> 4108[0m     indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39m_get_indexer_strict(key, [38;5;124m"[39m[38;5;124mcolumns[39m[38;5;124m"[39m)[[38;5;241m1[39m]
[1;32m   4110[0m [38;5;66;03m# take() does not accept boolean indexers[39;00m
[1;32m   4111[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(indexer, [38;5;124m"[39m[38;5;124mdtype[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m) [38;5;241m==[39m [38;5;28mbool[39m:

File [0;32m~/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/pandas/core/indexes/base.py:6200[0m, in [0;36mIndex._get_indexer_strict[0;34m(self, key, axis_name)[0m
[1;32m   6197[0m [38;5;28;01melse[39;00m:
[1;32m   6198[0m     keyarr, indexer, new_indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_reindex_non_unique(keyarr)
[0;32m-> 6200[0m [38;5;28mself[39m[38;5;241m.[39m_raise_if_missing(keyarr, indexer, axis_name)
[1;32m   6202[0m keyarr [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtake(indexer)
[1;32m   6203[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, Index):
[1;32m   6204[0m     [38;5;66;03m# GH 42790 - Preserve name from an Index[39;00m

File [0;32m~/opt/anaconda3/envs/jupyterbook_env/lib/python3.11/site-packages/pandas/core/indexes/base.py:6249[0m, in [0;36mIndex._raise_if_missing[0;34m(self, key, indexer, axis_name)[0m
[1;32m   6247[0m [38;5;28;01mif[39;00m nmissing:
[1;32m   6248[0m     [38;5;28;01mif[39;00m nmissing [38;5;241m==[39m [38;5;28mlen[39m(indexer):
[0;32m-> 6249[0m         [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNone of [[39m[38;5;132;01m{[39;00mkey[38;5;132;01m}[39;00m[38;5;124m] are in the [[39m[38;5;132;01m{[39;00maxis_name[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m)
[1;32m   6251[0m     not_found [38;5;241m=[39m [38;5;28mlist[39m(ensure_index(key)[missing_mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m]][38;5;241m.[39munique())
[1;32m   6252[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mnot_found[38;5;132;01m}[39;00m[38;5;124m not in index[39m[38;5;124m"[39m)

[0;31mKeyError[0m: "None of [Index(['name1', 'name2', 'name3'], dtype='object')] are in the [columns]"

